# Generated by Django 4.2.1 on 2023-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2023-05-24'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='gender', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default='4.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(default='lname', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default='01000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.CharField(default='20210000', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(default='fname', max_length=50),
        ),
    ]
