# Generated by Django 4.2.1 on 2023-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_sid_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departement',
            field=models.CharField(default='none', max_length=2),
        ),
    ]
