# Generated by Django 4.2.1 on 2023-05-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='departement',
            field=models.CharField(default='none', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2023-05-24', verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(default='First name', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default='4.00', max_digits=3, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='20210000', max_length=8, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(default='Last name', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default='01000000000', max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Active', 'inActive')], max_length=8),
        ),
    ]
