# Generated by Django 4.2.1 on 2023-05-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_departement_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='departement',
            field=models.CharField(choices=[('NULL', 'NULL'), ('CS', 'CS'), ('AI', 'AI'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], default='NULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=8),
        ),
    ]
