# Generated by Django 4.2.1 on 2023-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_email_alter_student_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2023/05/24', verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='20210000', error_messages={'unique': 'The ID you entered is not unique.'}, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('level 1', 'level 1'), ('level 2', 'level 2'), ('level 3', 'level 3'), ('level 4', 'level 4')], default='level 1', max_length=7),
        ),
    ]
