# Generated by Django 4.2.1 on 2023-05-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_dob_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2023-05-24', verbose_name='Date Of Birth'),
        ),
    ]
