# Generated by Django 4.2.1 on 2023-05-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='departement',
            field=models.CharField(choices=[('NULL', 'NULL'), ('CS', 'CS'), ('AI', 'AI'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], default='NULL', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
